// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.mark.grpc.demo.provider.user;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mark_grpc_demo_provider_user_UserRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mark_grpc_demo_provider_user_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mark_grpc_demo_provider_user_UserResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mark_grpc_demo_provider_user_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nuser.proto\022 com.mark.grpc.demo.provide" +
      "r.user\" \n\013UserRequest\022\021\n\tuser_name\030\001 \001(\t" +
      "\"2\n\014UserResponse\022\017\n\007user_id\030\001 \001(\005\022\021\n\tuse" +
      "r_name\030\002 \001(\t2y\n\013UserService\022j\n\007getUser\022-" +
      ".com.mark.grpc.demo.provider.user.UserRe" +
      "quest\032..com.mark.grpc.demo.provider.user" +
      ".UserResponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mark_grpc_demo_provider_user_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mark_grpc_demo_provider_user_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mark_grpc_demo_provider_user_UserRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_mark_grpc_demo_provider_user_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mark_grpc_demo_provider_user_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mark_grpc_demo_provider_user_UserResponse_descriptor,
        new String[] { "UserId", "UserName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
