// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.mark.grpc.demo.provider.user;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mark.grpc.demo.provider.user.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string user_name = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
