// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.mark.grpc.demo.provider.user;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mark.grpc.demo.provider.user.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string user_name = 2;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string user_name = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
